### ISSUE TITLE
Transverse field four times smaller?

### ISSUE THREAD

**Issue by ryuikaneko** [issp-center-dev/dsqss#22]
Hi,

The transverse field "Gamma" given in the XXZ model seems four times smaller in PMWA (ver.2.0.2).
I attach std.in for the 1D FM TFIsing model (L=8,beta=8) and comparison of Mx vs. Gamma with that in the thermodynamic limit at T=0 (fig_L8_beta8.png, fig_L8_beta8_Gamma_rescaled.png).

[std.in](https://github.com/issp-center-dev/dsqss/files/4998386/std.in.txt)

original:
![fig_L8_beta8](https://user-images.githubusercontent.com/27846552/88872756-e8529200-d255-11ea-9254-15e514a2348b.png)

Gamma rescaled:
![fig_L8_beta8_Gamma_rescaled](https://user-images.githubusercontent.com/27846552/88872753-e7b9fb80-d255-11ea-856b-3fb55da589cb.png)

Ryui

**Comment by yomichi** [comment]
@ryuikaneko 
I'm sorry for the late reply and thank you for reporting.
I found that we had a mistake in the transformation of Hamiltonian from the spin system to the bosonic system.
(the factor of 4 came from division by 2 instead of multiplication by 2)

I will release a new bug-fixed release v2.0.3 in a couple of days.

**Comment by ryuikaneko** [comment]
Great!
